/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DomesticRouteImport } from './routes/domestic'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as InfoRouteImport } from './routes/info'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WhyOnlineRouteImport } from './routes/why-online'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountBookingsRouteImport } from './routes/account.bookings'
import { Route as AccountBookingsIdRouteImport } from './routes/account.bookings.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DomesticRoute = DomesticRouteImport.update({
  id: '/domestic',
  path: '/domestic',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyOnlineRoute = WhyOnlineRouteImport.update({
  id: '/why-online',
  path: '/why-online',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/account/bookings',
  path: '/account/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookingsIdRoute = AccountBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/domestic': typeof DomesticRoute
  '/flights': typeof FlightsRoute
  '/info': typeof InfoRoute
  '/international': typeof InternationalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/why-online': typeof WhyOnlineRoute
  '/account/bookings': typeof AccountBookingsRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/account/bookings/$id': typeof AccountBookingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/domestic': typeof DomesticRoute
  '/flights': typeof FlightsRoute
  '/info': typeof InfoRoute
  '/international': typeof InternationalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/why-online': typeof WhyOnlineRoute
  '/account/bookings': typeof AccountBookingsRouteWithChildren
  '/account': typeof AccountIndexRoute
  '/account/bookings/$id': typeof AccountBookingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/domestic': typeof DomesticRoute
  '/flights': typeof FlightsRoute
  '/info': typeof InfoRoute
  '/international': typeof InternationalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/why-online': typeof WhyOnlineRoute
  '/account/bookings': typeof AccountBookingsRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/account/bookings/$id': typeof AccountBookingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/domestic'
    | '/flights'
    | '/info'
    | '/international'
    | '/reset-password'
    | '/why-online'
    | '/account/bookings'
    | '/account/'
    | '/account/bookings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/domestic'
    | '/flights'
    | '/info'
    | '/international'
    | '/reset-password'
    | '/why-online'
    | '/account/bookings'
    | '/account'
    | '/account/bookings/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/domestic'
    | '/flights'
    | '/info'
    | '/international'
    | '/reset-password'
    | '/why-online'
    | '/account/bookings'
    | '/account/'
    | '/account/bookings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DomesticRoute: typeof DomesticRoute
  FlightsRoute: typeof FlightsRoute
  InfoRoute: typeof InfoRoute
  InternationalRoute: typeof InternationalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WhyOnlineRoute: typeof WhyOnlineRoute
  AccountBookingsRoute: typeof AccountBookingsRouteWithChildren
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domestic': {
      id: '/domestic'
      path: '/domestic'
      fullPath: '/domestic'
      preLoaderRoute: typeof DomesticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-online': {
      id: '/why-online'
      path: '/why-online'
      fullPath: '/why-online'
      preLoaderRoute: typeof WhyOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/bookings': {
      id: '/account/bookings'
      path: '/account/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/bookings/$id': {
      id: '/account/bookings/$id'
      path: '/$id'
      fullPath: '/account/bookings/$id'
      preLoaderRoute: typeof AccountBookingsIdRouteImport
      parentRoute: typeof AccountBookingsRoute
    }
  }
}

interface AccountBookingsRouteChildren {
  AccountBookingsIdRoute: typeof AccountBookingsIdRoute
}

const AccountBookingsRouteChildren: AccountBookingsRouteChildren = {
  AccountBookingsIdRoute: AccountBookingsIdRoute,
}

const AccountBookingsRouteWithChildren = AccountBookingsRoute._addFileChildren(
  AccountBookingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DomesticRoute: DomesticRoute,
  FlightsRoute: FlightsRoute,
  InfoRoute: InfoRoute,
  InternationalRoute: InternationalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WhyOnlineRoute: WhyOnlineRoute,
  AccountBookingsRoute: AccountBookingsRouteWithChildren,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
