// This file is automatically generated. Do not edit it directly.
// Note: Modified to fix createMiddleware import issue on Vercel
import type { createMiddleware as tanstackCreateMiddleware } from '@tanstack/react-start'
import { supabase } from './client'
import { createMiddleware as createMiddlewareWrapper } from '@/lib/middleware-factory'

// Use TanStack's createMiddleware if available, fallback to our wrapper
let createMiddleware: typeof tanstackCreateMiddleware
try {
  const tanstackMiddleware = require('@tanstack/react-start').createMiddleware
  createMiddleware =
    typeof tanstackMiddleware === 'function'
      ? tanstackMiddleware
      : createMiddlewareWrapper
} catch {
  createMiddleware = createMiddlewareWrapper
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
